### ISSUE TITLE
Where Is the Mods List Backup?

### ISSUE THREAD

**Issue by GalGreenfield** [Garethp/Vortex-Modlist-Backup#6]
Hello,

Where is the mods list backup file?

Also, when I go to Vortex to the `Extensions` page this is what I get - should it be like this?
![](https://i.imgur.com/r6EQTlm.png)

I'm on Linux but running Vortex via Lutris, and it works just fine.
If it's a path issue then I don't see where I can change it manually in the JS file.

**Comment by Garethp** [comment]
If you go to the page for your game, there should be a new button in the top menu to create the backup file. When you select it, it'll ask you where to save that file.

![67-1574711459-1788149758](https://user-images.githubusercontent.com/709912/89090968-2b1f8180-d39e-11ea-9087-0c5db86211ce.png)
