### ISSUE TITLE
Open file instead of creating one

### ISSUE THREAD

**Issue by nfsc30001** [Garethp/Vortex-Modlist-Backup#8]
When i try to backup my mod list it prompts me to open a file to export to, but i couldnt find anywhere what kind of file it wanted so i tried writing it to a txt file but the i get the error shown in the screenshot.
<img width="418" alt="Annotation 2020-08-06 234232" src="https://user-images.githubusercontent.com/4419767/89585652-83db9800-d83e-11ea-9b48-46538f9a2daa.png">

**Comment by Garethp** [comment]
Thanks for this report, I'll try to get a fix out this weekend for that
