### ISSUE TITLE
Invalid Extension

### ISSUE THREAD

**Issue by mujahidean1** [Garethp/Vortex-Modlist-Backup#9]
![image](https://user-images.githubusercontent.com/69552894/89960514-275deb80-dc37-11ea-97d0-a0bc2dd02445.png)

![image](https://user-images.githubusercontent.com/69552894/89960797-e1555780-dc37-11ea-8bb8-611ead31c55f.png)

Doesn't work with Vortex

**Comment by Garethp** [comment]
Try either downloading it from [the releases page](https://github.com/Garethp/Vortex-Modlist-Backup/releases/) or from [the nexus mods page](https://www.nexusmods.com/site/mods/67)
